#nullable enable

using Crusaders30XX.ECS.Data.Ids;
using Crusaders30XX.ECS.DataOriented.Definitions;
using Crusaders30XX.ECS.DataOriented.Resources;

namespace Crusaders30XX.ECS.DataOriented.Content.Enemies;

internal static class EnemyAttackDefinitionDataTable
{
    public static readonly EnemyAttackDefinitionData[] Values =
    [
        A(EnemyAttackId.PummelIntoSubmission, "Pummel Into Submission", 6, EnemyAttackCondition.IfNotBlockedByAtLeastTwoCards, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.HitHook, text: "Intimidate 1. If not blocked by at least 2 cards, gain 1 scar."),
        A(EnemyAttackId.TreeStomp, "Tree Stomp", 9, flags: EnemyAttackFlags.RevealHook, text: "Intimidate 2."),
        A(EnemyAttackId.SlamTrunk, "Slam Trunk", 4, flags: EnemyAttackFlags.RevealHook, text: "Intimidate 1."),
        A(EnemyAttackId.FakeOut, "Fake Out", 3, flags: EnemyAttackFlags.RevealHook, text: "Intimidate 2."),
        A(EnemyAttackId.Thud, "Thud", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, gain 1 wounded."),
        A(EnemyAttackId.BoneStrike, "Bone Strike", 2, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, visual: RuleVisualEffectRecipeIds.EnemySlash, text: "On hit, gain 1 scar."),
        A(EnemyAttackId.Sweep, "Sweep", 4, flags: EnemyAttackFlags.RevealHook, text: "On reveal, a random hand card gains recoil 1."),
        A(EnemyAttackId.Calcify, "Calcify", 2, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, enemy gains 2 guard."),
        A(EnemyAttackId.SkullCrusher, "Skull Crusher", 9),
        A(EnemyAttackId.PiercingShot, "Piercing Shot", 4, flags: EnemyAttackFlags.RevealHook, text: "On attack, deal 2 effect damage."),
        A(EnemyAttackId.WeatheringShot, "Weathering Shot", 5, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, apply brittle to each blocking card."),
        A(EnemyAttackId.QuickShot, "Quick Shot", 6),
        A(EnemyAttackId.Snipe, "Snipe", 10, flags: EnemyAttackFlags.IgnoresAegis, text: "Ignores aegis."),
        A(EnemyAttackId.Slice, "Slice", 1),
        A(EnemyAttackId.Dice, "Dice", 1),
        A(EnemyAttackId.DuskFlick, "Dusk Flick", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, gain 1 wounded."),
        A(EnemyAttackId.CloakedReaver, "Cloaked Reaver", 3),
        A(EnemyAttackId.SilencingStab, "Silencing Stab", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, freeze 3 random cards in hand/draw pile."),
        A(EnemyAttackId.SharpenBlade, "Sharpen Blade", 2, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, enemy gains 3 aggression."),
        A(EnemyAttackId.ShadowStep, "Shadow Step", 3, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.BlockerHook, text: "Blocking cards lose 2 block for the quest unless this is the final battle."),
        A(EnemyAttackId.NightveilGuillotine, "Nightveil Guillotine", 4, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.DynamicDamage, text: "If Slice and Dice hit this turn, gain 4 damage."),
        A(EnemyAttackId.RazorMaw, "Razor Maw", 9, EnemyAttackCondition.DamageThreshold, threshold: 7, flags: EnemyAttackFlags.ThresholdHook, visual: RuleVisualEffectRecipeIds.EnemyBite, text: "If this deals at least 3 damage, gain 1 burn."),
        A(EnemyAttackId.ScorchingClaw, "Scorching Claw", 10, EnemyAttackCondition.IfNotBlockedByAtLeastTwoCards, flags: EnemyAttackFlags.HitHook, visual: RuleVisualEffectRecipeIds.EnemyClawSlash, text: "If not blocked by at least 2 cards, gain 1 burn."),
        A(EnemyAttackId.InfernalExecution, "Infernal Execution", 8, EnemyAttackCondition.MustBlockWithAtLeastTwoCards, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.ChannelHook, text: "On attack, gain burn increased by channel. Must block with at least 2 cards."),
        A(EnemyAttackId.Pounce, "Pounce", 5, guard: 0),
        A(EnemyAttackId.TutorialHordeStrike, "Pounce", 9, guard: 0),
        A(EnemyAttackId.TutorialHordeStrike3, "Pounce", 3, guard: 0),
        A(EnemyAttackId.TutorialHordeStrike5, "Pounce", 5, guard: 0),
        A(EnemyAttackId.TutorialHordeStrike6, "Pounce", 6, guard: 0),
        A(EnemyAttackId.TutorialHordeStrike7, "Pounce", 7, guard: 0),
        A(EnemyAttackId.TutorialHordeStrike8, "Pounce", 8, guard: 0),
        A(EnemyAttackId.TutorialHordeStrike9, "Pounce", 9, guard: 0),
        A(EnemyAttackId.SandBlast, "Sand Blast", 4, guard: 0, visual: RuleVisualEffectRecipeIds.EnemyRockBlast),
        A(EnemyAttackId.SandStorm, "Sand Storm", 3, guard: 0),
        A(EnemyAttackId.TutorialSandBlast, "Sand Blast", 4, guard: 0),
        A(EnemyAttackId.TutorialSandStorm, "Sand Storm", 3, guard: 0),
        A(EnemyAttackId.SandPound, "Sand Pound", 7, EnemyAttackCondition.MustBlockWithExactlyOneCard, flags: EnemyAttackFlags.RevealHook, visual: RuleVisualEffectRecipeIds.EnemyRockBlast, text: "Must be blocked with exactly 1 card/equipment."),
        A(EnemyAttackId.SandSlam, "Sand Slam", 10, EnemyAttackCondition.MustBlockWithExactlyTwoCards, flags: EnemyAttackFlags.RevealHook, text: "Must be blocked with exactly 2 cards/equipment."),
        A(EnemyAttackId.SuffocatingSilk, "Suffocating Silk", 10, EnemyAttackCondition.DamageThreshold, 6, 7, flags: EnemyAttackFlags.ThresholdHook | EnemyAttackFlags.DynamicThreshold, text: "If this deals at least 3-4 damage, gain 4 slow."),
        A(EnemyAttackId.MandibleBreaker, "Mandible Breaker", 10, EnemyAttackCondition.IfNotBlockedByAtLeastOneCard, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.HitHook, text: "Intimidate 1. If unblocked, gain 1 fear."),
        A(EnemyAttackId.Entomb, "Entomb", 10, EnemyAttackCondition.DamageThreshold, 6, 7, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.ThresholdHook | EnemyAttackFlags.DynamicThreshold, text: "If threshold is met, brittle the top draw card."),
        A(EnemyAttackId.Mummify, "Mummify", 10, EnemyAttackCondition.DamageThreshold, 6, 7, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.ThresholdHook | EnemyAttackFlags.DynamicThreshold, text: "If threshold is met, gain 2 scars."),
        A(EnemyAttackId.Leprosy, "Leprosy", 9, flags: EnemyAttackFlags.RevealHook, text: "On attack, 2 random hand cards become brittle."),
        A(EnemyAttackId.VelvetFangs, "Velvet Fangs", 4, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.HitHook, visual: RuleVisualEffectRecipeIds.EnemyBite, text: "Heal 1 HP per courage lost this battle."),
        A(EnemyAttackId.SoulSiphon, "Soul Siphon", 3, EnemyAttackCondition.OnHit, restriction: EnemyAttackColorRestriction.NotRed, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.HitHook, text: "Only non-red cards can block. On hit, lose 1 courage."),
        A(EnemyAttackId.EnthrallingGaze, "Enthralling Gaze", 3),
        A(EnemyAttackId.CrushingAdoration, "Crushing Adoration", 2, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, enemy gains 2 aggression."),
        A(EnemyAttackId.TeasingNip, "Teasing Nip", 2, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, 50% chance to lose 1 courage."),
        A(EnemyAttackId.SawtoothRend, "Sawtooth Rend", 9, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.BlockerHook, text: "Gain 2 bleed per blocker matching the selected color."),
        A(EnemyAttackId.DustStorm, "Dust Storm", 8, EnemyAttackCondition.MustBlockWithAtLeastOneCard, flags: EnemyAttackFlags.RevealHook, text: "Must be blocked with at least 1 card/equipment."),
        A(EnemyAttackId.StrangeForce, "Strange Force", 11, EnemyAttackCondition.IfNotBlockedByAtLeastTwoColors, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.HitHook, text: "Draw 1 and intimidate 1. If not blocked by 2 colors, mill 1."),
        A(EnemyAttackId.IcyBlade, "Icy Blade", 11, EnemyAttackCondition.IfNotBlockedByAtLeastTwoCards, flags: EnemyAttackFlags.HitHook, text: "If not blocked by 2 cards, gain 2 frostbite."),
        A(EnemyAttackId.FrozenClaw, "Frozen Claw", 10, EnemyAttackCondition.DamageThreshold, threshold: 6, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.ThresholdHook, visual: RuleVisualEffectRecipeIds.EnemyClawSlash, text: "Intimidate 1. If this deals 4+ damage, freeze top draw card."),
        A(EnemyAttackId.FrostEater, "Frost Eater", 9, flags: EnemyAttackFlags.ProgressHook, text: "Frozen blockers have -1 block."),
        A(EnemyAttackId.GlacialStrike, "Glacial Strike", 8, EnemyAttackCondition.MustBlockWithAtLeastOneCard, flags: EnemyAttackFlags.RevealHook, text: "Must be blocked with at least 1 card/equipment."),
        A(EnemyAttackId.GlacialBlast, "Glacial Blast", 11, EnemyAttackCondition.MustBlockWithAtLeastTwoCards, flags: EnemyAttackFlags.RevealHook, text: "Must be blocked with at least 2 cards/equipment."),
        A(EnemyAttackId.Cinderbolt, "Cinderbolt", 10, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.BlockerHook, text: "Gain 1 burn if a selected-color card blocks."),
        A(EnemyAttackId.InsidiousBolt, "Insidious Bolt", 10, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.BlockerHook, text: "Gain 2 scars if a selected-color card blocks."),
        A(EnemyAttackId.Rage, "Rage", 9),
        A(EnemyAttackId.TrainingStrike, "Training Strike", 9, visual: RuleVisualEffectRecipeIds.EnemySlash),
        A(EnemyAttackId.ShadowStrike, "Shadow Strike", 10, EnemyAttackCondition.DamageThreshold, threshold: 7, flags: EnemyAttackFlags.ThresholdHook, text: "If this deals 3+ damage, enemy loses 1 anathema."),
        A(EnemyAttackId.DissipatingDarkness, "Encroaching Darkness", 10, EnemyAttackCondition.IfNotBlockedByAtLeastTwoCards, flags: EnemyAttackFlags.HitHook, text: "If not blocked by 2 cards, enemy gains 1 anathema."),
        A(EnemyAttackId.SnuffOutTheLight, "Snuff Out the Light", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, gain 1 silenced."),
        A(EnemyAttackId.NightFall, "Night Fall", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, enemy loses 1 anathema."),
        A(EnemyAttackId.FromTheShadows, "From the Shadows", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.RevealHook, text: "Intimidate 1."),
        A(EnemyAttackId.UmbraSlice, "Umbra Slice", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, gain 1 scar."),
        A(EnemyAttackId.TremorStrike, "Tremor Strike", 9, EnemyAttackCondition.IfNotBlockedByAtLeastTwoCards, flags: EnemyAttackFlags.HitHook, text: "If not blocked by 2 cards, gain 2 shackled."),
        A(EnemyAttackId.StoneBarrage, "Stone Barrage", 10, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.BlockerHook, visual: RuleVisualEffectRecipeIds.EnemyRockBlast, text: "Gain 2 bleed per blocker matching the selected color."),
        A(EnemyAttackId.EarthenWall, "Earthen Wall", 6, flags: EnemyAttackFlags.RevealHook, text: "On attack, enemy gains 4 guard."),
        A(EnemyAttackId.HaveNoMercy, "Have No Mercy", 5, EnemyAttackCondition.IfNotBlockedByAtLeastOneCard, flags: EnemyAttackFlags.RevealHook, text: "Mark a card to discard if unblocked."),
        A(EnemyAttackId.Gaze, "Gaze", 2, EnemyAttackCondition.OnHit, maxDamage: 5, flags: EnemyAttackFlags.DynamicDamage | EnemyAttackFlags.HitHook, text: "On hit, top draw card gains 3 seals."),
        A(EnemyAttackId.BasiliskGlare, "Basilisk Glare", 2, EnemyAttackCondition.OnHit, maxDamage: 5, flags: EnemyAttackFlags.DynamicDamage | EnemyAttackFlags.RevealHook | EnemyAttackFlags.ConfirmHook, text: "Cannot be blocked by sealed cards."),
        A(EnemyAttackId.SerpentStrike, "Serpent Strike", 2, EnemyAttackCondition.OnHit, maxDamage: 5, flags: EnemyAttackFlags.DynamicDamage | EnemyAttackFlags.HitHook, text: "On hit, all sealed cards gain 1 seal."),
        A(EnemyAttackId.PetrifyingGaze, "Petrifying Gaze", 2, maxDamage: 5, flags: EnemyAttackFlags.DynamicDamage | EnemyAttackFlags.BlockerHook, text: "Each blocking card gains 2 seals."),
        A(EnemyAttackId.StoneSkin, "Stone Skin", 2, maxDamage: 5, flags: EnemyAttackFlags.DynamicDamage | EnemyAttackFlags.ProgressHook, text: "Sealed cards block for 1 less."),
        A(EnemyAttackId.VipersCurse, "Viper's Curse", 1, maxDamage: 3, flags: EnemyAttackFlags.DynamicDamage | EnemyAttackFlags.RevealHook, text: "Random hand card gains 2 seals."),
        A(EnemyAttackId.CrumblingStone, "Crumbling Stone", 2, maxDamage: 5, flags: EnemyAttackFlags.DynamicDamage | EnemyAttackFlags.BlockerHook, text: "Blocking cards lose 2 seals."),
        A(EnemyAttackId.WyvernStrike, "Talon Swipe", 10),
        A(EnemyAttackId.WyvernThreat, "Rend & Ruin", 10, EnemyAttackCondition.IfNotBlockedByAtLeastTwoCards, flags: EnemyAttackFlags.HitHook, text: "If not blocked by 2 cards, discard the plundered card."),
        A(EnemyAttackId.FallenShepherdPhase1, "Cast Out", 9, EnemyAttackCondition.MustBlockWithAtLeastOneCard, flags: EnemyAttackFlags.RevealHook | EnemyAttackFlags.BlockerHook, text: "Must block with 1. Blocking cards become colorless."),
        A(EnemyAttackId.FallenShepherdCrooksScar, "Crook's Scar", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, gain 1 scar."),
        A(EnemyAttackId.FallenShepherdBreakFaith, "Break Faith", 3, flags: EnemyAttackFlags.BlockerHook, text: "Blocking cards become brittle."),
        A(EnemyAttackId.FallenShepherdBloodletting, "Bloodletting", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, gain 3 bleed."),
        A(EnemyAttackId.FallenShepherdCowTheFlock, "Cow the Flock", 3, flags: EnemyAttackFlags.RevealHook, text: "Intimidate 1."),
        A(EnemyAttackId.FallenShepherdPhase2, "Binding Sermon", 10, EnemyAttackCondition.DamageThreshold, 6, 7, flags: EnemyAttackFlags.DynamicThreshold | EnemyAttackFlags.ThresholdHook, text: "If threshold is met, gain 2 shackled."),
        A(EnemyAttackId.FallenShepherdShepherdsVigil, "Shepherd's Vigil", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, enemy gains 3 guard."),
        A(EnemyAttackId.FallenShepherdHush, "Hush", 3, EnemyAttackCondition.OnHit, flags: EnemyAttackFlags.HitHook, text: "On hit, gain 1 silenced."),
        A(EnemyAttackId.FallenShepherdPhase3, "Have No Mercy", 9, EnemyAttackCondition.DamageThreshold, 3, 4, flags: EnemyAttackFlags.DynamicThreshold | EnemyAttackFlags.RevealHook | EnemyAttackFlags.ThresholdHook, text: "If threshold is met, discard the marked card."),
        A(EnemyAttackId.FallenShepherdPurgeTheHeretic, "Purge the Heretic", 8, flags: EnemyAttackFlags.RevealHook, text: "On reveal, gain 1 burn."),
        A(EnemyAttackId.FallenShepherdFearTheShepherd, "Fear the Shepherd", 9, flags: EnemyAttackFlags.RevealHook, text: "On reveal, gain 1 fear."),
        A(EnemyAttackId.FallenShepherdFinalSermon, "Final Sermon", 9, flags: EnemyAttackFlags.RevealHook, text: "On reveal, gain 1 silenced."),
    ];

    private static EnemyAttackDefinitionData A(
        EnemyAttackId id,
        string name,
        int damage,
        EnemyAttackCondition condition = EnemyAttackCondition.None,
        int threshold = 0,
        int thresholdMax = 0,
        int guard = 75,
        EnemyAttackFlags flags = EnemyAttackFlags.None,
        VisualEffectRecipeId visual = default,
        int maxDamage = 0,
        EnemyAttackColorRestriction restriction = EnemyAttackColorRestriction.None,
        string text = "") =>
        new(
            id,
            name,
            damage,
            maxDamage == 0 ? damage : maxDamage,
            0,
            condition,
            restriction,
            0,
            threshold,
            thresholdMax == 0 ? threshold : thresholdMax,
            guard,
            flags,
            visual,
            text);
}
