namespace Crusaders30XX.ECS.Generators;

internal static class AttributeSource
{
    public const string Text = """
// <auto-generated />
#nullable enable

namespace Crusaders30XX.ECS.DataOriented.Generated
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    internal sealed class EcsQueryAttribute : global::System.Attribute
    {
        public EcsQueryAttribute(string stableId, params global::System.Type[] returnedTypes)
        {
            StableId = stableId;
            ReturnedTypes = returnedTypes;
        }

        public string StableId { get; }

        public global::System.Type[] ReturnedTypes { get; }

        public global::System.Type[] All { get; set; } = global::System.Array.Empty<global::System.Type>();

        public global::System.Type[] Any { get; set; } = global::System.Array.Empty<global::System.Type>();

        public global::System.Type[] None { get; set; } = global::System.Array.Empty<global::System.Type>();

        public bool IncludeDisabled { get; set; }
    }
}
""";
}
